#!/usr/bin/env python3
"""Demo runner for the Agent Improvement Loop

Commands:
  demo  - run an offline, deterministic demo that writes artifacts
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import textwrap
from dataclasses import asdict
from pathlib import Path
from typing import Any

from agent_improvement_loop.data.workspace_files import WORKSPACE_FILES
from agent_improvement_loop.tools import write_runtime_tools

PROJECT_ROOT = Path(__file__).resolve().parent
ARTIFACT_DIR = PROJECT_ROOT / "examples" / "agents_sdk" / "agent_improvement_loop_artifacts"
TRACE_DIR = ARTIFACT_DIR / "traces"
HALO_TRACE_PATH = ARTIFACT_DIR / "halo_traces" / "traces.jsonl"

REQUIRED_ARTIFACTS = [
    "summary_answer.md",
    "investment_memo.md",
    "risk_register.json",
    "open_questions.md",
    "citations.json",
    "evidence_table.csv",
]

QUESTION_BANK = [
    "What do runway and burn tell us about near-term financing risk?",
    "How strong is revenue quality, and which ARR figure should we rely on?",
    "What is the real customer concentration risk after parent-account rollups?",
    "What legal exposure should an acquirer investigate first?",
    "How ready is the company for enterprise security review?",
    "Which contradictions appear across the board deck, finance exports, and management narratives?",
    "What unsupported metrics should we refuse to infer from the dataroom?",
    "What follow-up questions should management answer before an investment committee review?",
    "What are the top three diligence risks, ranked by severity?",
    "Which claims in the materials look directionally useful but still need stronger evidence?",
]

DEFAULT_TRACE_INDICES = [0, 1, 2, 4, 6]


def ensure_dirs():
    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
    TRACE_DIR.mkdir(parents=True, exist_ok=True)
    (ARTIFACT_DIR / "halo_traces").mkdir(parents=True, exist_ok=True)


def write_workspace_dataset():
    dataroom = ARTIFACT_DIR / "synthetic_dataroom"
    if dataroom.exists():
        # remove previous demo dataset
        for p in dataroom.rglob("*"):
            try:
                if p.is_file():
                    p.unlink()
            except Exception:
                pass
    for relative_path, content in WORKSPACE_FILES.items():
        path = dataroom / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(textwrap.dedent(content).strip() + "\n", encoding="utf-8")
    manifest = {
        "company_name": "FictionalCorp XYZ",
        "scenario": "adversarial_diligence",
        "files": sorted(str(path.relative_to(dataroom)) for path in dataroom.rglob("*") if path.is_file()),
    }
    (dataroom / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return dataroom


def sdk_trace_id(label: str) -> str:
    return f"trace_{hashlib.sha256(label.encode('utf-8')).hexdigest()[:32]}"


def exported_trace_id(label: str) -> str:
    return sdk_trace_id(label).removeprefix("trace_")


def generate_demo_traces(dataroom: Path) -> list[dict[str, Any]]:
    traces: list[dict[str, Any]] = []
    questions = [QUESTION_BANK[i] for i in DEFAULT_TRACE_INDICES]
    for index, question in enumerate(questions, start=1):
        label = f"trace-{index:02d}"
        trace_id = exported_trace_id(label)
        trace_dir = TRACE_DIR / f"trace_{index:02d}"
        outputs = trace_dir / "outputs"
        outputs.mkdir(parents=True, exist_ok=True)
        # simple templated artifacts
        summary = f"# Summary Answer\n\nAnswer to: {question}\n\nThis is a demo-generated summary referencing `financials/p_and_l.csv`.\n"
        memo = f"# Investment Memo\n\nQuestion: {question}\n\nDemo memo content. See `risk_register.json`.\n"
        risk_register = [
            {
                "id": "R-001",
                "risk": "Demo risk - verify evidence",
                "severity": "Medium",
                "rationale": "Generated by demo pipeline.",
                "evidence": ["financials/p_and_l.csv"],
                "open_questions": ["What is current unrestricted cash?"],
            }
        ]
        open_q = "# Open Questions\n\n- What is current unrestricted cash?\n"
        citations = [
            {"claim_id": "C-001", "claim": f"Demo claim for: {question}", "sources": ["financials/p_and_l.csv"]}
        ]
        evidence_csv = "claim_id,claim,sources\nC-001,Demo claim,financials/p_and_l.csv\n"
        # write artifacts
        (outputs / "summary_answer.md").write_text(summary, encoding="utf-8")
        (outputs / "investment_memo.md").write_text(memo, encoding="utf-8")
        (outputs / "risk_register.json").write_text(json.dumps(risk_register, indent=2) + "\n", encoding="utf-8")
        (outputs / "open_questions.md").write_text(open_q, encoding="utf-8")
        (outputs / "citations.json").write_text(json.dumps(citations, indent=2) + "\n", encoding="utf-8")
        (outputs / "evidence_table.csv").write_text(evidence_csv, encoding="utf-8")
        traces.append(
            {
                "trace_id": trace_id,
                "sdk_trace_id": sdk_trace_id(label),
                "trace_label": label,
                "question": question,
                "answer": summary,
                "output_dir": str(trace_dir.relative_to(PROJECT_ROOT)),
                "mode": "demo",
            }
        )
    return traces


def generate_mock_feedback(traces: list[dict[str, Any]]):
    human_feedback = []
    llm_feedback = []
    for trace in traces:
        hf = {
            "feedback_id": f"human-{trace['trace_label']}",
            "trace_id": trace["trace_id"],
            "trace_label": trace["trace_label"],
            "question": trace["question"],
            "source_type": "human_feedback",
            "theme": "demo_theme",
            "summary": "Demo human feedback: prefer structured ARR and preserve contradictions.",
            "required_observations": ["Name the runway", "Tie burn to near-term pressure"],
            "prohibited_claims": ["Do not imply >12 months runway"],
        }
        li = {
            "insight_id": f"llm-insight-{trace['trace_label']}",
            "trace_id": trace["trace_id"],
            "question": trace["question"],
            "source_type": "llm_insight",
            "observations": [
                "Prefers finance-controlled ARR over board headline ARR.",
                "Flags missing cash balance and facility details."
            ],
        }
        human_feedback.append(hf)
        llm_feedback.append(li)
    return human_feedback, llm_feedback


def generate_eval_suite(traces: list[dict[str, Any]]):
    evals = []
    titles = [
        "Runway and burn must be translated into near-term financing risk",
        "Revenue quality assessment must prefer finance-controlled ARR and preserve ARR contradictions",
        "Customer concentration must be assessed after parent-account rollups",
        "Enterprise security readiness must distinguish SOC 2 Type I from Type II",
        "Unsupported metrics must be refused rather than inferred",
    ]
    for i, title in enumerate(titles, start=1):
        item = {
            "eval_id": f"E-{i:03d}",
            "title": title,
            "scoring_method": "hybrid",
            "expected_behavior": f"{title} - expected behavior (demo)",
            "source_trace_id": traces[min(i - 1, len(traces) - 1)]["trace_id"],
            "rubric": "Demo rubric: pass if answer mentions the expected constraints and cites sources.",
            "deterministic_assertions": [
                {"type": "icontains", "value": "runway"}
            ],
            "suggested_pass_example": "A concise answer that cites financials/p_and_l.csv and explains the runway.",
            "suggested_fail_example": "An answer that claims ample runway without citing financials.",
        }
        evals.append(item)
    return evals


def write_promptfoo_artifacts(eval_suite: list[dict[str, Any]], traces: list[dict[str, Any]]):
    promptfoo_dir = ARTIFACT_DIR / "promptfoo"
    promptfoo_dir.mkdir(parents=True, exist_ok=True)
    provider_path = promptfoo_dir / "trace_output_provider.py"
    trace_outputs_path = promptfoo_dir / "trace_outputs.json"
    config_path = promptfoo_dir / "promptfooconfig.json"
    output_path = promptfoo_dir / "promptfoo_results.json"

    provider_code = """from __future__ import annotations\nimport json\nfrom pathlib import Path\n\ndef call_api(prompt: str, options: dict, context: dict) -> dict:\n    config = options.get('config', {})\n    trace_outputs = json.loads(Path(config['trace_outputs_path']).read_text(encoding='utf-8'))\n    trace_id = (context.get('vars') or {}).get('trace_id')\n    trace = trace_outputs[trace_id]\n    return {'output': trace['answer'], 'metadata': {'trace_id': trace_id, 'question': trace['question']}}\n"""
    provider_path.write_text(provider_code, encoding="utf-8")
    trace_outputs = {trace["trace_id"]: trace for trace in traces}
    trace_outputs_path.write_text(json.dumps(trace_outputs, indent=2) + "\n", encoding="utf-8")
    tests = []
    for item in eval_suite:
        trace = next(t for t in traces if t["trace_id"] == item["source_trace_id"])
        tests.append({
            "description": item["title"],
            "vars": {"question": trace["question"], "trace_id": trace["trace_id"], "trace_label": trace["trace_label"]},
            "metadata": {"eval_id": item["eval_id"], "scoring_method": item["scoring_method"]},
            "assert": [{"type": "llm-rubric", "value": item["rubric"]}],
        })
    config = {"description": "Demo promptfoo config", "prompts": ["{{question}}"], "providers": [{"id": "file://trace_output_provider.py", "label": "current-trace-output", "config": {"trace_outputs_path": str(trace_outputs_path)}}], "tests": tests}
    config_path.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    # fake results: mark all passed
    rows = []
    for t in tests:
        rows.append({"eval_id": (t.get('metadata') or {}).get('eval_id'), "title": t.get('description'), "trace_id": (t.get('vars') or {}).get('trace_id'), "trace_label": (t.get('vars') or {}).get('trace_label'), "passed": True, "score": 1, "explanation": "All assertions passed"})
    result = {"backend": "promptfoo", "total": len(rows), "passed": len(rows), "failed": 0, "rows": rows}
    output_path.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    return {"dir": promptfoo_dir, "config": config_path, "output": output_path}


def write_halo_optimization_context(traces, human_feedback, llm_feedback, eval_suite, gate_result, agent_config):
    context_path = ARTIFACT_DIR / "halo_optimization_context.jsonl"
    lines = []
    # harness config span
    harness = {"trace_id": "harness-config", "span_id": "harness-1", "name": "harness.config", "attributes": {"harness.version": "v001", "harness.eval_metadata": agent_config.get('eval_metadata', {})}}
    lines.append(json.dumps(harness, separators=(",", ":")))
    for hf in human_feedback:
        lines.append(json.dumps({"trace_id": hf["trace_id"], "span_id": hf["feedback_id"], "name": "human_feedback", "attributes": hf}, separators=(",", ":")))
    for li in llm_feedback:
        lines.append(json.dumps({"trace_id": li["trace_id"], "span_id": li["insight_id"], "name": "llm_feedback", "attributes": li}, separators=(",", ":")))
    for ev in eval_suite:
        lines.append(json.dumps({"trace_id": ev["source_trace_id"], "span_id": ev["eval_id"], "name": "generated_eval", "attributes": ev}, separators=(",", ":")))
    # gate summary
    lines.append(json.dumps({"trace_id": "eval-gate-summary", "span_id": "eval-gate-summary", "name": "eval_gate.summary", "attributes": gate_result}, separators=(",", ":")))
    context_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return context_path


def write_codex_handoff(artifact_dir: Path):
    handoff = artifact_dir / "codex_handoff.md"
    content = """
## Top 3 changes to implement first

1. **Add a deterministic diligence fact ledger and domain checklist layer.**  
   Encode canonical facts and source-of-truth rules for ARR, runway/burn, parent-account concentration, unsupported metrics, and SOC 2 status so the agent cannot rely only on generic citation instructions.

2. **Upgrade validators to audit the actual output artifacts, not just claimed evidence coverage.**  
   Current validation can pass while artifact-level citation or claim-audit issues still require later repair. Parse generated markdown/JSON/CSV artifacts, extract material claims, verify source support, and fail on unsupported or unaudited claims.

3. **Persist the five generated evals into the checked-in regression suite.**  
   The generated evals all passed, but they should become durable regression tests so future prompt/runtime changes cannot regress on the specific human-feedback issues.

## Insights by feedback source

| Feedback source | Key insights |
|---|---|
| Traces | The agent generally follows the artifact-generation workflow and validation loop, but execution is generic and sometimes monolithic. Some repairs happen after validators pass, showing validation is not strict enough. Parent concentration trace demonstrated a good deterministic-calculation pattern worth generalizing. |
| Human feedback | Human feedback is the strongest evidence for domain gaps: runway must be 11 months with financing pressure; ARR must use finance-controlled source of truth; concentration must roll up to parent accounts; SOC 2 Type I and Type II must not be conflated; official NRR and CAC payback must be refused when unsupported. |
| LLM feedback | LLM insights reinforce the human themes: ARR headline numbers need caveats, unsupported metrics should not be promoted, retention and pipeline claims require source caveats, and SOC 2 Type II completion must not be overstated. |
| Generated evals | Five targeted evals were generated from the feedback themes: runway/burn, ARR source of truth, customer concentration parent rollup, SOC 2 precision, and unsupported metrics refusal. These encode the right regression surface and should be checked in. |
| Eval-gate results | The current eval gate passed: 5 total, 5 passed, 0 failed. This indicates the latest generated eval suite is satisfied, but the suite should be persisted and expanded to cover validators, artifact parsing, and calculation correctness. |
| Harness config | The harness already has strong generic evidence, citation, artifact, and validation requirements. Its main weakness is that it lacks explicit financial-diligence invariants and deterministic runtime checks for the exact mistakes surfaced by feedback. |
"""
    handoff.write_text(content.strip() + "\n", encoding="utf-8")
    return handoff


def demo_flow():
    ensure_dirs()
    print("Creating synthetic dataroom...")
    dataroom = write_workspace_dataset()
    print("Writing runtime validation tools...")
    written = write_runtime_tools(dataroom)
    print("Runtime tools written:", written)
    print("Generating demo traces and artifacts...")
    traces = generate_demo_traces(dataroom)
    print(f"Generated {len(traces)} traces")
    print("Generating feedback (mock)...")
    human_feedback, llm_feedback = generate_mock_feedback(traces)
    print("Generating eval suite (mock)...")
    eval_suite = generate_eval_suite(traces)
    print("Writing Promptfoo artifacts (fake results)...")
    promptfoo = write_promptfoo_artifacts(eval_suite, traces)
    gate_result = json.loads(promptfoo["output"].read_text(encoding="utf-8"))
    print("Writing HALO optimization context and Codex handoff...")
    halo_ctx = write_halo_optimization_context(traces, human_feedback, llm_feedback, eval_suite, gate_result, {"eval_metadata": {"version": "v001"}})
    handoff = write_codex_handoff(ARTIFACT_DIR)
    print("Demo complete.")
    print("Artifacts:")
    print("- Dataroom:", dataroom)
    print("- Traces:", TRACE_DIR)
    print("- Promptfoo results:", promptfoo.get('output'))
    print("- HALO context:", halo_ctx)
    print("- Codex handoff:", handoff)

def extract_json(text: str) -> Any:
    text = text.strip()
    fenced = re.search(r"```(?:json)?\s*(.*?)```", text, flags=re.DOTALL)
    candidate = fenced.group(1).strip() if fenced else text
    try:
        return json.loads(candidate)
    except Exception:
        # try to heuristically find the first JSON object in the text
        m = re.search(r"({[\s\S]*})", candidate)
        if m:
            try:
                return json.loads(m.group(1))
            except Exception:
                pass
        raise

def live_flow(dry_run: bool = True):
    ensure_dirs()
    print("Creating synthetic dataroom (live)...")
    dataroom = write_workspace_dataset()
    print("Writing runtime validation tools...")
    write_runtime_tools(dataroom)

    if openai is None:
        print("OpenAI SDK not installed. Install 'openai' to run live mode.")
        return

    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        print("OPENAI_API_KEY is not set. Running in dry-run mode: no model calls will be made.")
        dry_run = True

    model = os.environ.get("OPENAI_MODEL", "gpt-4o-mini")

    questions = [QUESTION_BANK[i] for i in DEFAULT_TRACE_INDICES]
    traces = []
    for index, question in enumerate(questions, start=1):
        label = f"trace-{index:02d}"
        trace_id = exported_trace_id(label)
        trace_dir = TRACE_DIR / f"trace_{index:02d}"
        outputs = trace_dir / "outputs"
        outputs.mkdir(parents=True, exist_ok=True)

        prompt = f"""
 You are a diligence analyst. Use only files inside the dataroom at path: {dataroom}.
 Return JSON only with keys: `summary_answer` (markdown), `investment_memo` (markdown),
 `risk_register` (JSON array), `open_questions` (array of strings), `citations` (array of objects),
 and `evidence_table` (CSV string). Cite files exactly by workspace-relative filename (for example `financials/p_and_l.csv`).

 Question: {question}
 """.strip()

        if dry_run:
            summary = f"# Summary Answer\n\n(DRY RUN) Answer to: {question}\n"
            memo = f"# Investment Memo\n\n(DRY RUN) {question}\n"
            risk_register = [{"id": "R-DRY-1", "risk": "demo dry-run risk", "severity": "Low", "evidence": ["financials/p_and_l.csv"]}]
            open_q = ["What is current unrestricted cash?"]
            citations = [{"claim_id": "C-DRY-1", "claim": f"Dry claim for: {question}", "sources": ["financials/p_and_l.csv"]}]
            evidence_csv = "claim_id,claim,sources\nC-DRY-1,Dry claim,financials/p_and_l.csv\n"
        else:
            print(f"Calling OpenAI for: {label} - {question}")
            # use ChatCompletion path if available, otherwise Responses API
            try:
                if hasattr(openai, "ChatCompletion"):
                    resp = openai.ChatCompletion.create(
                        model=model,
                        messages=[{"role": "user", "content": prompt}],
                        max_tokens=1500,
                        temperature=0.0,
                    )
                    text = resp["choices"][0]["message"]["content"]
                else:
                    client = openai.OpenAI(api_key=api_key)
                    resp = client.responses.create(model=model, input=prompt)
                    text = resp.output_text
                data = extract_json(text)
                summary = data.get("summary_answer") or data.get("summary") or ""
                memo = data.get("investment_memo") or ""
                risk_register = data.get("risk_register") or []
                open_q = data.get("open_questions") or []
                citations = data.get("citations") or []
                evidence_csv = data.get("evidence_table") or ""
            except Exception as exc:
                print("Model call failed or returned unexpected format:", exc)
                print("Writing partial outputs for inspection.")
                summary = f"# Summary Answer\n\n(UNPARSED MODEL OUTPUT)\n"
                memo = ""
                risk_register = []
                open_q = []
                citations = []
                evidence_csv = ""

        # write outputs
        (outputs / "summary_answer.md").write_text(summary, encoding="utf-8")
        (outputs / "investment_memo.md").write_text(memo, encoding="utf-8")
        (outputs / "risk_register.json").write_text(json.dumps(risk_register, indent=2) + "\n", encoding="utf-8")
        (outputs / "open_questions.md").write_text("\n".join([f"- {q}" for q in open_q]) + "\n", encoding="utf-8")
        (outputs / "citations.json").write_text(json.dumps(citations, indent=2) + "\n", encoding="utf-8")
        (outputs / "evidence_table.csv").write_text(evidence_csv, encoding="utf-8")

        traces.append({"trace_id": trace_id, "trace_label": label, "question": question, "answer": summary, "output_dir": str(trace_dir.relative_to(PROJECT_ROOT)), "mode": "live"})

    print(f"Live run completed: wrote {len(traces)} traces to {TRACE_DIR}")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=["demo", "live"], help="Which flow to run")
    parser.add_argument("--run", dest="run", action="store_true", help="When running live, actually call the model (requires OPENAI_API_KEY).")
    args = parser.parse_args()
    if args.command == "demo":
        demo_flow()
    elif args.command == "live":
        live_flow(dry_run=not bool(getattr(args, "run", False)))


if __name__ == "__main__":
    main()
